server:
  port: 8001

spring:
  application:
    name: consumer_1
  cloud:
    config:
      uri: http://localhost:8888 #it's optional by default it will listen to 8888 on your localhost
    bus:
      destination: producerBus
  config:
    import: "configserver:" #This property is necessary to ensure that the application fetches its configuration from the Config Server.

# allow all Actuator endpoints to be exposed.
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false # disables security for the Actuator endpoints.

#Shows informational messages that highlight the progress of the application at a coarse-grained level.
logging:
  level:
    org:
      springframework: INFO