server:
  port: 8888

spring:
  application:
    name: producer-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/static/
    bus:
      destination: producerBus #change the default name(springCloudBus) of the rabbitmq exchange
  profiles:
    active: native #activate native search in our path (/static/*)

# allow all Actuator endpoints to be exposed.
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false # disables security for the Actuator endpoints.

#Shows informational messages that highlight the progress of the application at a coarse-grained level.
logging:
  level:
    org:
      springframework: INFO



#spring cloud bus can detect which rabbitmq server start on your machine
## rabbitmq definitions are optional
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest